# --- Theme (Catppuccin Mocha) --- (fallback defaults, overridden below by wallust)
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC

# Cursor
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# URL underline color when hovering
url_color               #F5E0DC

# Window borders
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F38BA8

# Tab bar
wayland_titlebar_color  system
macos_titlebar_color    system

# Colors for 16 color terminal
# black
color0 #45475A
color8 #585B70
# red
color1 #F38BA8
color9 #F38BA8
# green
color2  #A6E3A1
color10 #A6E3A1
# yellow
color3  #F9E2AF
color11 #F9E2AF
# blue
color4  #89B4FA
color12 #89B4FA
# magenta
color5  #F5C2E7
color13 #F5C2E7
# cyan
color6  #94E2D5
color14 #94E2D5
# white
color7  #BAC2DE
color15 #A6ADC8

# --- Aesthetics & Spacing ---
background_opacity 0.85
window_padding_width 12
confirm_os_window_close 0

# --- Font ---
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.5
allow_remote_control yes
sync_to_monitor no
cursor_blink_interval 0
cursor_trail 0
include current-theme.conf
hide_window_decorations yes
