backend = "resized"
color_space = "lab"
threshold = 20
palette = "kmeans"

[templates.kde]
template = "Wallust.colors"
target = "/home/YOUR_USERNAME/.local/share/color-schemes/Wallust.colors"

[templates.kitty]
template = "colors-kitty.conf"
target = "/home/YOUR_USERNAME/.config/kitty/current-theme.conf"

[templates.fastfetch]
template = "fastfetch.jsonc"
target = "/home/YOUR_USERNAME/.config/fastfetch/config.jsonc"

[templates.starship]
template = "starship.toml"
target = "/home/YOUR_USERNAME/.config/starship.toml"

[templates.gtk3]
template = "gtk3-colors.css"
target = "/home/YOUR_USERNAME/.config/gtk-3.0/gtk.css"

[templates.gtk4]
template = "gtk4-colors.css"
target = "/home/YOUR_USERNAME/.config/gtk-4.0/gtk.css"

[templates.cava]
template = "cava-config"
target = "/home/YOUR_USERNAME/.config/cava/config"

[templates.conky]
template = "conky-mocha.conf"
target = "/home/YOUR_USERNAME/.config/conky/mocha.conf"

[templates.btop]
template = "btop-wallust.theme"
target = "/home/YOUR_USERNAME/.config/btop/themes/wallust.theme"

[templates.spicetify]
template = "spicetify-user.css"
target = "/home/YOUR_USERNAME/.config/spicetify/Themes/wallust/user.css"

[templates.vim]
template = "vim-colors.vim"
target = "/home/YOUR_USERNAME/.cache/wallust/wallust.vim"

[templates.mpv]
template = "mpv-colors.conf"
target = "/home/YOUR_USERNAME/.config/mpv/colors.conf"

[templates.discord]
template = "discord-vencord.css"
target = "/home/YOUR_USERNAME/.config/vesktop/settings/quickCss.css"

[templates.zen]
template = "zen-userchrome.css"
target = "/home/YOUR_USERNAME/.config/zen/YOUR_PROFILE.Default (release)/chrome/userChrome.css"

[templates.fzf]
template = "fzf-colors.sh"
target = "/home/YOUR_USERNAME/.cache/wallust/fzf.sh"

[templates.bat]
template = "bat-wallust.tmTheme"
target = "/home/YOUR_USERNAME/.config/bat/themes/Wallust.tmTheme"

[templates.grub]
template = "grub-theme.txt"
target = "/home/YOUR_USERNAME/.cache/wallust/grub-theme.txt"

[templates.sddm]
template = "sddm-theme.conf"
target = "/home/YOUR_USERNAME/.cache/wallust/sddm-theme.conf"

[templates.eza]
template = "eza-colors.sh"
target = "/home/YOUR_USERNAME/.cache/wallust/eza.sh"

[templates.android-studio]
template = "android-studio.icls"
target = "/home/YOUR_USERNAME/.config/Google/AndroidStudioXXXX.X/colors/Wallust.icls"

[templates.android-studio-ui-theme]
template = "android-studio.theme.json"
target = "/home/YOUR_USERNAME/.cache/wallust/plasmalust.theme.json"

[templates.kvantum]
template = "kvantum-plasmalust.kvconfig"
target = "/home/YOUR_USERNAME/.config/Kvantum/Plasmalust/Plasmalust.kvconfig"

[templates.ksplash]
template = "ksplash-plasmalust.qml"
target = "/home/YOUR_USERNAME/.cache/wallust/ksplash-Splash.qml"

[templates.wallpaper-overlay]
template = "wallpaper-overlay.qml"
target = "/home/YOUR_USERNAME/.cache/wallust/wallpaper-overlay.qml"

[templates.menu-overlay]
template = "menu-overlay.qml"
target = "/home/YOUR_USERNAME/.cache/wallust/menu-overlay.qml"
