# Generated by wallust - do not edit directly
# EZA_COLORS uses semicolon-separated SGR codes (38;2;R;G;B for truecolor
# foreground), not wallust's own comma-separated `| rgb` filter output, so
# the hex-to-decimal conversion happens here at shell-source time instead
# of in the template - same technique set-theme itself already uses for
# the KDE accent color.
#
# The hex args below MUST stay quoted ("{{color4}}" not {{color4}}) - an
# unquoted #rrggbb as the first character of a word starts a bash comment
# and eats the rest of the line, which breaks the whole export silently
# until you actually try to source it.
_wallust_rgb() { printf '%d;%d;%d' "0x${1:1:2}" "0x${1:3:2}" "0x${1:5:2}"; }
export EZA_COLORS="di=1;38;2;$(_wallust_rgb "{{color4}}"):ex=1;38;2;$(_wallust_rgb "{{color2}}"):ln=1;38;2;$(_wallust_rgb "{{color6}}"):or=1;38;2;$(_wallust_rgb "{{color1}}"):fi=38;2;$(_wallust_rgb "{{foreground}}"):pi=38;2;$(_wallust_rgb "{{color3}}"):so=38;2;$(_wallust_rgb "{{color5}}"):bd=38;2;$(_wallust_rgb "{{color3}}"):cd=38;2;$(_wallust_rgb "{{color3}}"):uu=38;2;$(_wallust_rgb "{{color4}}"):xa=38;2;$(_wallust_rgb "{{color8}}")"
unset -f _wallust_rgb
