# Generated by wallust - do not edit directly
export FZF_DEFAULT_OPTS="--color=fg:{{foreground}},bg:{{background}},hl:{{color4}},fg+:{{foreground}},bg+:{{color0}},hl+:{{color4}},info:{{color3}},prompt:{{color1}},pointer:{{color5}},marker:{{color2}},spinner:{{color5}},header:{{color6}}"
