" Generated by wallust - do not edit directly
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "wallust"

hi Normal       guifg={{foreground}} guibg={{background}}
hi Cursor       guifg={{background}} guibg={{cursor}}
hi CursorLine   guibg={{color8}}     cterm=NONE
hi CursorLineNr guifg={{color4}}     guibg=NONE
hi LineNr       guifg={{color8}}     guibg=NONE
hi Visual       guibg={{color8}}
hi Search       guifg={{background}} guibg={{color3}}
hi IncSearch    guifg={{background}} guibg={{color1}}
hi Comment      guifg={{color8}}     gui=italic
hi Constant     guifg={{color5}}
hi String       guifg={{color2}}
hi Identifier   guifg={{color6}}
hi Function     guifg={{color4}}
hi Statement    guifg={{color1}}
hi PreProc      guifg={{color5}}
hi Type         guifg={{color3}}
hi Special      guifg={{color6}}
hi Pmenu        guifg={{foreground}} guibg={{color0}}
hi PmenuSel     guifg={{background}} guibg={{color4}}
hi StatusLine   guifg={{background}} guibg={{color4}}
hi StatusLineNC guifg={{foreground}} guibg={{color0}}
hi VertSplit    guifg={{color0}}     guibg={{color0}}
hi ErrorMsg     guifg={{color1}}     guibg=NONE
hi WarningMsg   guifg={{color3}}     guibg=NONE
hi DiffAdd      guibg={{color2}}     guifg={{background}}
hi DiffDelete   guibg={{color1}}     guifg={{background}}
hi DiffChange   guibg={{color3}}     guifg={{background}}
hi DiffText     guibg={{color3}}     guifg={{background}} gui=bold
