#!/bin/bash
# One-time panel layout/branding cleanup - not part of the recurring
# set-theme pipeline since these are structural settings, not
# palette-driven ones (the Kickoff icon's *color* is handled dynamically
# in set-theme itself; this just wires up the icon path + everything else).
#
# - Kickoff (app launcher) icon: Garuda's cat logo -> wallust-recolored Arch
#   logo (~/.cache/wallust/panel-logo.png, generated by set-theme).
# - User switcher: turn off the account-color avatar circle (not
#   wallust-themeable - it's the user's account color from System
#   Settings), fall back to a plain icon that follows the icon theme.
# - System tray: hide the microphone privacy indicator and Garuda System
#   Maintenance icon - both are fixed-asset/fixed-size icons from their
#   own processes, not real systray plasmoids, so they can't be resized or
#   recolored to match; hiding (not disabling) keeps them reachable from
#   the "show hidden icons" flyout.
# - Top panel: enable Plasma's native floating-panel mode (rounded
#   corners, edge gap, drop shadow), and bump its height from the default
#   32px to 40px - too thin for the systray to comfortably scale/center
#   its icons in, even with scaleIconsToFit on. Both are live Containment
#   properties, not config file keys - not persisted anywhere obvious via
#   grep, but confirmed to survive plasmashell restarts, so set once here
#   via scripting rather than needing to run on every set-theme call.
set -euo pipefail

kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc \
    --group Containments --group 33 --group Applets --group 34 --group Configuration --group General \
    --key icon "$HOME/.cache/wallust/panel-logo.png"

kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc \
    --group Containments --group 33 --group Applets --group 54 --group Configuration --group General \
    --key showFace false

kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc \
    --group Containments --group 33 --group Applets --group 41 --group General \
    --key hiddenItems "plasmashell_microphone,Garuda System Maintenance"

kquitapp6 plasmashell 2>/dev/null || true
for i in $(seq 1 20); do pgrep -x plasmashell >/dev/null 2>&1 || break; sleep 0.5; done
kstart plasmashell >/dev/null 2>&1 &
disown
sleep 4

qdbus6 org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '
    var ps = panels();
    for (var i = 0; i < ps.length; i++) {
        if (ps[i].location == "top") {
            ps[i].floating = true;
            ps[i].height = 40;
        }
    }
'

echo "Panel layout applied. Run set-theme once more to generate the recolored logo."
